# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b21e336459d39d9e923b4ea589428972fad0bf9fd66ad60845ed0d0e3cf6334957582f62ec37e6b13bd32cd40403bd50a9fcc281bbf19497c9b0f040fb4fa8cf

test:
  secret_key_base: b38136d23a13df101d46d1b793962f20cb52d898fdfb783e8edb56c8d43ab3f50c06a997075bc472700155aa3ae5d3321f60c73cc15c587abdb7a14ee27ae889

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
